// Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

AWS_ACCOUNT_ID                         = "552309615171"
APP                                    = "daivi"
ENV                                    = "ref1"
AWS_PRIMARY_REGION                     = "us-east-1"
S3_KMS_KEY_ALIAS                       = "daivi-ref1-s3-secret-key"
S3_TABLES_KMS_KEY_ALIAS                = "daivi-ref1-s3tables-secret-key"
INVENTORY_DATA_FILE                    = "s3://552309615171-daivi-ref1-finops-inventory-s3-glue-s3-target/initial-inventory-report.csv.gz"
GLUE_ROLE_NAME                         = "daivi-ref1-glue-role"
INVENTORY_DATA_SOURCE_BUCKET_NAME      = "552309615171-daivi-ref1-finops-inventory-s3-glue-s3-source"
INVENTORY_DATA_TARGET_BUCKET_NAME      = "552309615171-daivi-ref1-finops-inventory-s3-glue-s3-target"
INVENTORY_DATA_SOURCE_BUCKET           = "s3://552309615171-daivi-ref1-finops-inventory-s3-glue-s3-source/"
INVENTORY_DATA_TARGET_BUCKET           = "s3://552309615171-daivi-ref1-finops-inventory-s3-glue-s3-target/"
INVENTORY_ICEBERG_BUCKET               = "s3://552309615171-daivi-ref1-finops-inventory-s3-glue-s3-iceberg/"
GLUE_SPARK_LOGS_BUCKET                 = "s3://552309615171-daivi-ref1-glue-spark-logs/"
GLUE_TEMP_BUCKET                       = "s3://552309615171-daivi-ref1-glue-temp/"
GLUE_KMS_KEY_ALIAS                     = "daivi-ref1-glue-secret-key"
CLOUDWATCH_KMS_KEY_ALIAS               = "daivi-ref1-cloudwatch-secret-key"
EVENTBRIDGE_ROLE_NAME                  = "daivi-ref1-eventbridge-role"
GLUE_SCRIPTS_BUCKET_NAME               = "552309615171-daivi-ref1-glue-scripts"
